baseURL = 'https://vipulbhasin.netlify.app/'
languageCode = 'en-us'
title = "Vipul Bhasin's blog"
theme = 'archie'
copyright = '© Vipul'

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "G-CJFB1MEE4L"

[pagination]
    pagerSize = 4

[params]
	favicon = "https://img.icons8.com/officel/16/000000/chevron-right.png"
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=true # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Musings on adventures in golang"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/vipulbhasin23"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/vipulbhasinn"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/bhasinvipul"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4